name: xdm-visualization
on:
  push:
jobs:
  xdm-visualization:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.13'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: git clone https://github.com/adobe/xdmVisualization.git
      - run: cd xdmVisualization
      - run: echo "test"
      - run: bundle install
      - run: npm install -g grunt-cli
      - run: npm install
      - run: ./scripts/xdmVisual4Git.sh master

